#!/bin/sh
#++++++++++++++++
# Copyright:    (C) 2008-2017 UDS/CNRS
# License:       GNU General Public License
#.IDENTIFICATION findcfhtw
#.VERSION  1.0   31-Oct-2014
#.PURPOSE        Find Stars in CFHT-LS Wide or Deep
#----------------

D_BIN=`dirname $0`
pgm=`basename $0`
dr=`echo $0 | rev | cut -c1 | tr dw DW`
cat=CFHT-LS_${dr}1to4

# No argument is assumed to call for help
test $# -eq 0 && exec $0 -help

# Use the generic find_gen service
exec $D_BIN/find_gen1 $cat "$@"
