#!/bin/sh
#++++++++++++++++
# Copyright:    (C) 2008-2017 UDS/CNRS
# License:       GNU General Public License
#.IDENTIFICATION findurat1
#.VERSION  1.0   ?????
#.VERSION  1.1   04-Feb-2016
#.PURPOSE        Find Stars in URAT1
#----------------

D_BIN=`dirname $0`
pgm=`basename $0`
cat=URAT1

# No argument is assumed to call for help
test $# -eq 0 && exec $0 -help

# Use the generic find_gen service
exec $D_BIN/find_gen1 $cat "$@"
