#!/bin/sh
#++++++++++++++++
# Copyright:    (C) 2008-2017 UDS/CNRS
# License:       GNU General Public License
#.IDENTIFICATION findgalex
#.VERSION  1.0   31-Oct-2014
#.PURPOSE        Find Stars in GALEX preliminary (slim) version
#----------------

D_BIN=`dirname $0`
pgm=`basename $0`
dr=`echo $0 | rev | cut -c2 | tr am AM`
sv=`echo $0 | rev | cut -c1 | tr am AM`
cat=GALEX_GR${dr}_${sv}IS

# No argument is assumed to call for help
test $# -eq 0 && exec $0 -help

# Use the generic find_gen service
exec $D_BIN/find_gen1 $cat "$@"
