#!/bin/sh
#++++++++++++++++
# Copyright:    (C) 2008-2017 UDS/CNRS
# License:       GNU General Public License
#.IDENTIFICATION finducac2
#.LANGUAGE       Bourne shell
#.AUTHOR         Francois Ochsenbein [CDS]
#.ENVIRONMENT    CDSclient Scripts
#.KEYWORDS       UCAC2 catalog
#.VERSION  2.0   23-Aug-2009: Bourne shell
#.PURPOSE        Find Stars in UCAC2
#.COMMENTS       The "CDSCLIENT" env. variable indicates node ,
#		 eventually preceded by 'http:'
#----------------

D_BIN=`dirname $0`
pgm=`basename $0`
rpc=`basename $0 | sed 's/find//'`

# No argument is assumed to call for help
test $# -eq 0 && exec $0 -help

# Use the generic find_gen service
exec $D_BIN/find_gen $pgm $rpc "$@"
