#!/bin/csh -f
#++++++++++++++++
# Copyright:    (C) 2008-2017 UDS/CNRS
# License:       GNU General Public License
#.IDENTIFICATION findtycab
#.LANGUAGE       C-shell
#.AUTHOR         Francois Ochsenbein [CDS]
#.ENVIRONMENT    
#.KEYWORDS       
#.VERSION  1.0   24-Feb-1998
#.PURPOSE        Find one Star in TYCHO Photometry Annex B
#.COMMENTS       
#----------------
set D_BIN = `dirname $0`
set path = ($D_BIN /usr/local/bin /usr/bin /usr/ucb /bin)

set acl_con = "aclient cdsarc.u-strasbg.fr 1660"
set cgi_con = "aclient_cgi cdsarc.u-strasbg.fr"

set rcon="$acl_con"
which aclient |& grep -v ' ' >& /dev/null # note SUN needs the grep
if( $status > 0 || $?http_proxy ) set rcon="$cgi_con"

set pgm = `basename $0`
if ($?MACHINE) then
    set path = ($path /usr/$MACHINE/bin)
endif
$rcon tycab $argv:q
exit $status
