#!/bin/sh
#++++++++++++++++
# Copyright:    (C) 2008-2017 UDS/CNRS
# License:       GNU General Public License
#.IDENTIFICATION findusnob1
#.LANGUAGE       C-shell
#.AUTHOR         Francois Ochsenbein [CDS]
#.ENVIRONMENT    
#.KEYWORDS       
#.VERSION  1.0   02-Jun-2001
#.VERSION  1.1   16-Mar-2003: Accept other contraints than -c
#.VERSION  1.2   23-Jan-2007: Bug fxied in line 54 (thanks Thomas Erben)
#.VERSION  1.3   01-Sep-2008: for proxy usage
#.VERSION  1.4   30-Aug-2009: Bourne shell
#.PURPOSE        Find Stars in USNO-B1.0
#.COMMENTS       
#----------------

D_BIN=`dirname $0`
pgm=`basename $0`
rpc=`basename $0 | sed 's/find//'`

# No argument is assumed to call for help
test $# -eq 0 && exec $0 -help

# Use the generic find_gen service
exec $D_BIN/find_gen $pgm $rpc "$@"
