#!/bin/sh
#++++++++++++++++
# Copyright:    (C) 2008-2017 UDS/CNRS
# License:       GNU General Public License
#.IDENTIFICATION findwise
#.VERSION  1.0   23-Apr-2012
#.VERSION  1.1   31-Oct-2014: Several versions
#.PURPOSE        Find Stars in WISE catalogs
#----------------

D_BIN=`dirname $0`
pgm=`basename $0`

case $0 in
    *0) cat=WISE_ALLSKY; ;;
    *p) cat=WISE_PRELIM; ;;
     *) cat=ALLWISE; ;;
esac

# No argument is assumed to call for help
test $# -eq 0 && exec $0 -help

# Use the generic find_gen service
exec $D_BIN/find_gen1 $cat "$@"
