#!/bin/sh
#++++++++++++++++
# Copyright:    (C) 2008-2017 UDS/CNRS
# License:       GNU General Public License
#.IDENTIFICATION findnomad1
#.LANGUAGE       C-shell
#.AUTHOR         Francois Ochsenbein [CDS]
#.ENVIRONMENT    
#.KEYWORDS       
#.VERSION  1.0   06-Aug-2006
#.VERSION  1.1   01-Sep-2008: for proxy usage
#.VERSION  1.2   29-Aug-2009: Bourne Shell
#.PURPOSE        Find Stars in NOMAD-1 catalog
#----------------

D_BIN=`dirname $0`
pgm=`basename $0`
rpc=`basename $0 | sed 's/find//'`

# No argument is assumed to call for help
test $# -eq 0 && exec $0 -help

# Use the generic find_gen service
exec $D_BIN/find_gen $pgm $rpc "$@"

