#!/bin/sh
#++++++++++++++++
# Copyright:    (C) 2008-2017 UDS/CNRS
# License:       GNU General Public License
#.IDENTIFICATION findwisep
#.VERSION  1.0   23-Apr-2012
#.PURPOSE        Find Stars in WISE preliminary (slim) version
#----------------

D_BIN=`dirname $0`
pgm=`basename $0`
dr=`echo $0 | rev | cut -c1-2 | rev`
cat=CMC${dr}

# No argument is assumed to call for help
test $# -eq 0 && exec $0 -help

# Use the generic find_gen service
exec $D_BIN/find_gen1 $cat "$@"
