#!/bin/sh
#++++++++++++++++
# Copyright:    (C) 2008-2017 UDS/CNRS
# License:       GNU General Public License
#.IDENTIFICATION findglimpse
#.LANGUAGE       Bourne shell
#.AUTHOR         Francois Ochsenbein [CDS]
#.ENVIRONMENT    CDSclient Scripts
#.KEYWORDS       GLIMPSE (Spitzer)
#.VERSION  1.0   05-Apr-2010: Merged GLIMPSE-I + II
#.PURPOSE        Find Stars in GLIMPSE Catalog (II/293)
#----------------

D_BIN=`dirname $0`
pgm=`basename $0`
rpc=`basename $0 | sed 's/find//'`

# No argument is assumed to call for help
test $# -eq 0 && exec $0 -help

case "$1" in
     h*)  # Assume help
      exec $0 -help
      ;;
    -h*)  # Differs from standard help
    cat <<===Help
Usage: $pgm -help for more details; most useful possibilities are:
       $pgm J2000-center [other_options]
   or  $pgm -cg Galactic-center [other_options]
   or  $pgm -id GLIMPSE-id [other_options]
   or  $pgm -f [file_with_data] [other_options]
===Help
    exec $D_BIN/find_gen $pgm $rpc -rhelp
    ;;

  # Use the generic find_gen service
  *)
    exec $D_BIN/find_gen $pgm $rpc "$@"
    ;;
esac
