#!/bin/csh -f
#++++++++++++++++
# Copyright:    (C) 2008-2017 UDS/CNRS
# License:       GNU General Public License
#.IDENTIFICATION simbib
#.LANGUAGE       C-shell
#.AUTHOR         Francois Ochsenbein [CDS]
#.ENVIRONMENT    
#.KEYWORDS       
#.VERSION  1.0   13-Apr-1994
#.VERSION  1.1   21-Jun-1994: When no arg. provided, use help
#.PURPOSE        Query Simbad bibliography
#.COMMENTS       
#----------------
set D_BIN = `dirname $0`
set path = ($D_BIN /usr/local/bin /usr/bin /usr/ucb /bin)

set acl_con = "aclient cdsarc.u-strasbg.fr 1660"
set cgi_con = "aclient_cgi cdsarc.u-strasbg.fr"

set rcon="$acl_con"
which aclient |& grep -v ' ' >& /dev/null # note SUN needs the grep
if( $status > 0 || $?http_proxy ) set rcon="$cgi_con"

if ($#argv < 1) then
    $rcon simbib -help
    exit $status
endif
#
$rcon simbib $*:q 
exit $status
