name: macOS 11 Homebrew and MacPorts build

on: [push]

jobs:
  build_homebrew:

    runs-on: macos-latest

    # Manually enable/disable this test
    # Write an if statement that is always true/false
    if: true
    steps:
    - uses: actions/checkout@v4
    - name: brew update
      run: brew update
    # The following packages are were pre-installed
    # at a Github Actions VM, but not anymore
    # g++ and gfortran are part of the gcc package
    #- name: Install gcc, g++, gfortran, and wget
    #  run: brew install gcc wget
    #- name: Install X11 header files
    #  run: brew install libx11
    #- name: Install libpng
    #  run: brew install libpng
    - name: Install gcc/gfortran
      run: brew reinstall gcc
    - name: Install xquartz
      run: brew install --cask xquartz
    - name: Install shellcheck
      run: brew install shellcheck
    - name: Collect debug info
      run: |
        which gfortran
        brew info libx11
        ls -l /opt/homebrew/include/X11
        echo "Find GCC compiler"
        lib/find_gcc_compiler.sh
        echo "Find FORTRAN compiler"
        lib/find_fortran_compiler.sh
#    - name: Install xorg-server
#      run: brew install xorg-server
    - name: make VaST (Homebrew)
      run: make
    - name: Shellcheck VaST BASH scripts
      run: |
        for i in lib/*sh util/*sh util/transients/*sh util/examples/*sh; do
          shellcheck --severity=error $i
        done
    # Disble the long data analysis test
    #- name: prepare for the test
    #  run: echo "1" > ../THIS_IS_HPCC 
    #- name: test VaST
    #  run: util/examples/test_vast.sh

  build_macports:
    needs: build_homebrew
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check commit message
      id: check_commit
      run: |
        commit_message=$(git log --format=%B -n 1)
        if [[ "${commit_message}" == *"notest"* ]]; then
          echo "Commit contains 'notest'. Skipping tests."
          echo "SKIP=true" >> $GITHUB_ENV
        else
          echo "SKIP=false" >> $GITHUB_ENV
        fi
    - name: Install MacPorts
      run: |
        curl -LO https://raw.githubusercontent.com/GiovanniBussi/macports-ci/master/macports-ci
        source ./macports-ci install
      if: env.SKIP != 'true'
    - name: port upgrade outdated
      run: sudo port upgrade outdated
      if: env.SKIP != 'true'
    - name: Install gcc, g++, gfortran, and wget
      run: sudo port install gcc12 wget
      if: env.SKIP != 'true'
    - name: Install X11 header files
      run: sudo port install xorg-libX11
      if: env.SKIP != 'true'
    - name: Install libpng
      run: sudo port install libpng
      if: env.SKIP != 'true'
    - name: make VaST (MacPorts)
      run: make
      if: env.SKIP != 'true'
